<?php

$finder = PhpCsFixer\Finder::create();

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2'                   => true,
        '@Symfony'                => true,
        'align_multiline_comment' => true,
        'array_syntax'            => ['syntax' => 'short'],
        'binary_operator_spaces'  => [
            'default' => 'align_single_space_minimal',
            'operators' => [
                '=' =>'align_single_space_minimal',
                '=>' =>'align_single_space_minimal'
            ]
        ],
        'blank_line_after_namespace'          => true,
        'blank_line_before_statement'   => false,
        'braces'                              => true,
        'class_definition'                    => true,
        'class_keyword_remove'                => true,
        'combine_consecutive_issets'          => true,
        'combine_consecutive_unsets'          => true,
        'concat_space'                        => true,
        'dir_constant'                        => true,
        'elseif'                              => true,
        'encoding'                            => true,
        'full_opening_tag'                    => true,
        'function_declaration'                => true,
        'function_typehint_space'             => true,
        'is_null'                             => true,
        'line_ending'                         => true,
        'lowercase_constants'                 => true,
        'lowercase_keywords'                  => true,
        'mb_str_functions'                    => true,
        'method_argument_space'               => true,
        'method_separation'                   => true,
        'native_function_casing'              => true,
        'no_alias_functions'                  => true,
        'no_blank_lines_after_class_opening'  => true,
        'no_blank_lines_after_phpdoc'         => true,
        'no_closing_tag'                      => true,
        'no_empty_comment'                    => true,
        'no_empty_statement'                          => true,
        'no_extra_consecutive_blank_lines'            => true,
        'no_leading_namespace_whitespace'             => true,
        'no_mixed_echo_print'                         => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_multiline_whitespace_before_semicolons'   => true,
        'no_php4_constructor'                         => true,
        'no_singleline_whitespace_before_semicolons'  => true,
        'no_superfluous_elseif'                       => true,
        'no_trailing_whitespace'                      => true,
        'no_trailing_whitespace_in_comment'           => true,
        'no_unneeded_curly_braces'                    => true,
        'no_unused_imports'                           => true,
        'no_useless_else'                             => true,
        'no_useless_return'                           => true,
        'no_whitespace_before_comma_in_array'         => true,
        'no_whitespace_in_blank_line'                 => true,
        'non_printable_character'                     => true,
        'object_operator_without_whitespace'          => true,
        'ordered_class_elements'                      => true,
        'ordered_imports'                             => true,
        'phpdoc_align'                                => true,
        'phpdoc_order'                                => true,
        'phpdoc_scalar'                               => true,
        'protected_to_private'                        => true,
        'return_type_declaration'                     => ['space_before' => 'one'],
        'short_scalar_cast'                           => true,
        'single_blank_line_at_eof'                    => true,
        'single_blank_line_before_namespace'          => true,
        'single_line_after_imports'                   => true,
        'single_quote'                                => true,
        'trim_array_spaces'                           => true,
        'whitespace_after_comma_in_array'             => true,
    ])
    ->setFinder($finder);
